# .gitlab-ci.yml
image: node:12.16.2

before_script:
  - yarn install --frozen-lockfile

test:
  stage: test
  script: yarn jest --ci
  cache:
    paths:
    - node_modules/
    - .yarn

pages:
  script:
  - cd datalogui.dev
  - yarn install --frozen-lockfile
  - yarn build
  # - rm -rf public
  # - mv build public
  # - find build -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - datalogui.dev/build
  cache:
    paths:
    - node_modules/
    - .yarn
  only:
  - master

